### ISSUE TITLE
Implement "dcommit until here"

### ISSUE THREAD

**Issue by tarsius** [emacsorphanage/magit-svn#2]
_Please do not link back to the other issue - I don't want that guy to show up here._

> It was a great feature that only magit provided (no simple equivalent in git),

It seems to me, that the real problem is that `git svn dcommit` doesn't support the equivalent of `git push origin branch~5:branch`. It shouldn't be to hard to fake that though. What do you think, wouldn't that be even better than what we have now (doing two history-manipulations in parallel seems inherently dangerous)? This is how it would work:
1. Use interactive rebase to rearrange the not-yet-dcommitted commits, so that those you want to dcommit come first and only then the unfinished rest follows.
2. In "Unpushed git commits" move to the last commit to be dcommitted.
3. `M-x magit-svn-dcommit-until-here`, which would create and checkout a temporary branch (because that's what `git svn dcommit` needs), hard reset it to the last commit to be dcommitted, dcommit, checkout the real branch and rebase it onto what we got back from svn, and finally delete the temporary branch.

**Comment by tarsius** [comment]
By the way I also have another idea for a feature that could make "rewrite" unnecessary even when using svn. So don't be shy and let me know if you feel this doesn't solve the issue.

**Comment by tarsius** [comment]
@Niluge-KiWi have you seen this?

**Comment by Niluge-KiWi** [comment]
@tarsius I have (partly) followed this on the magit repo, and I have seen this issue here.

I have started using the magit interactive rebase instead of the old magit special rewrite, but I'm not yet really familiar with this.

Indeed the previous feature was useful: to be able to push only a first part of our local commits to svn.

However, from the git-svn man: (2.2.1, but it is also since at least git-svn 1.7.9.5 from ubuntu 12.04)

> dcommit
> ...
> When an optional Git branch name (or a Git commit object name) is specified as an argument, the subcommand works on the specified branch, not on the current branch.

So we do have the equivalent of `git push origin branch~5:branch` with `git svn dcommit`!
I haven't tested it though.

By default dcommit also rebase/reset after the svn commit, so maybe we should use `--no-rebase`, I'm not sure at all what we really want for this, but the option exists.

**Comment by tarsius** [comment]
We've been looking for a new maintainer for a long time now (#7). I am closing this issue, as I won't be implementing this myself and don't see anybody else doing it either. I also don't think it is essential.

> Indeed the previous feature was useful: to be able to push only a first part of our local commits to svn.

It's un-svn-ish, but I think that's what branches are for.
